# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: socio_validation.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'socio_validation.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16socio_validation.proto\x12\x0egymcore.socios\"?\n\x13ValidarSocioRequest\x12\x10\n\x08socio_id\x18\x01 \x01(\t\x12\x16\n\x0e\x63orrelation_id\x18\x02 \x01(\t\"e\n\x14ValidarSocioResponse\x12\x0e\n\x06\x65xiste\x18\x01 \x01(\x08\x12\r\n\x05\x61tivo\x18\x02 \x01(\x08\x12\x0c\n\x04nome\x18\x03 \x01(\t\x12\x0e\n\x06\x65stado\x18\x04 \x01(\t\x12\x10\n\x08mensagem\x18\x05 \x01(\t2s\n\x16SocioValidationService\x12Y\n\x0cValidarSocio\x12#.gymcore.socios.ValidarSocioRequest\x1a$.gymcore.socios.ValidarSocioResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'socio_validation_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VALIDARSOCIOREQUEST']._serialized_start=42
  _globals['_VALIDARSOCIOREQUEST']._serialized_end=105
  _globals['_VALIDARSOCIORESPONSE']._serialized_start=107
  _globals['_VALIDARSOCIORESPONSE']._serialized_end=208
  _globals['_SOCIOVALIDATIONSERVICE']._serialized_start=210
  _globals['_SOCIOVALIDATIONSERVICE']._serialized_end=325
# @@protoc_insertion_point(module_scope)
