# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from infrastructure.grpc import socio_validation_pb2 as socio__validation__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in socio_validation_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SocioValidationServiceStub:
    """Serviço exposto pelo Sócios-Service na porta 9001.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ValidarSocio = channel.unary_unary(
                '/gymcore.socios.SocioValidationService/ValidarSocio',
                request_serializer=socio__validation__pb2.ValidarSocioRequest.SerializeToString,
                response_deserializer=socio__validation__pb2.ValidarSocioResponse.FromString,
                _registered_method=True)


class SocioValidationServiceServicer:
    """Serviço exposto pelo Sócios-Service na porta 9001.
    """

    def ValidarSocio(self, request, context):
        """Valida se um sócio existe e devolve o seu estado actual.
        Usado pelo Treinos-Service antes de criar um plano de treino.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SocioValidationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ValidarSocio': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidarSocio,
                    request_deserializer=socio__validation__pb2.ValidarSocioRequest.FromString,
                    response_serializer=socio__validation__pb2.ValidarSocioResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'gymcore.socios.SocioValidationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('gymcore.socios.SocioValidationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SocioValidationService:
    """Serviço exposto pelo Sócios-Service na porta 9001.
    """

    @staticmethod
    def ValidarSocio(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gymcore.socios.SocioValidationService/ValidarSocio',
            socio__validation__pb2.ValidarSocioRequest.SerializeToString,
            socio__validation__pb2.ValidarSocioResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
